let chromium;
try{
 ({chromium}=require('playwright'));
}catch(firstError){
 const bundled=process.env.CODEX_PLAYWRIGHT_PATH||'/Users/mengnanjiang/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright';
 try{({chromium}=require(bundled))}catch(secondError){throw new Error('Playwright is required for check.cjs. Install playwright or set CODEX_PLAYWRIGHT_PATH. '+firstError.message)}
}
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('file://'+__dirname+'/index.html');
 const card=m=>p.locator(`.editor-card[data-method="${m}"]`),path=m=>card(m).locator('.editable-path').getAttribute('d');
 async function drag(locator,dx=24,dy=-11){const r=await locator.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2+dx,r.y+r.height/2+dy,{steps:5});await p.mouse.up()}
 async function clickPath(locator){const pt=await locator.evaluate(el=>{const q=el.getPointAtLength(el.getTotalLength()*.5),m=el.getScreenCTM();return{x:m.a*q.x+m.c*q.y+m.e,y:m.b*q.x+m.d*q.y+m.f}});await p.mouse.click(pt.x,pt.y)}
 if(await p.locator('#experienceScreen').isHidden()||!(await p.locator('#studyApp').isHidden())||!(await p.locator('#beginStudy').isDisabled())||await p.locator('input[name="svgExperience"]').count()!==3)throw Error('required SVG experience intro');
 const experienceLabels=await p.locator('.experience-option').allTextContents();if(!experienceLabels.some(t=>t.includes('Keine SVG-Erfahrung')&&t.includes('No SVG experience'))||!experienceLabels.some(t=>t.includes('Allgemeine SVG-Erfahrung')&&t.includes('General SVG experience'))||!experienceLabels.some(t=>t.includes('Sehr erfahren')&&t.includes('Highly experienced')))throw Error('bilingual SVG experience options');
 await p.locator('input[name="svgExperience"][value="general"]').check();if(await p.locator('#beginStudy').isDisabled())throw Error('experience selection gate');await p.locator('#beginStudy').click();if(!(await p.locator('#experienceScreen').isHidden())||await p.locator('#studyApp').isHidden())throw Error('experience intro transition');
 if(await p.locator('#taskBadge').textContent()!=='Übung 1 / 3 · Practice'||await card('practice').count()!==1)throw Error('practice screen');
 if(!(await p.locator('#progressBlock').isHidden())||!(await p.locator('#tutorialSteps').isHidden())||!(await p.locator('.target-panel').isHidden()))throw Error('simplified practice visibility');
 if(await p.locator('#export,[data-role="download"],#method,#nodeMode,#curve,#fit,.badge,[data-role="allHandles"],[data-role="geometry"]').count())throw Error('unused participant information remains');
 const gate=card('practice').locator('[data-role="startGate"]'),gateButton=card('practice').locator('[data-role="startGateButton"]'),gateBox=await gateButton.boundingBox();if(await gate.isHidden()||!(await card('practice').locator('[data-role="toggle"]').isHidden())||gateBox.width<190||gateBox.height<55)throw Error('large start gate');
 if(!(await card('practice').locator('[data-role="finish"]').isDisabled())||!(await card('practice').locator('[data-role="add"]').isDisabled()))throw Error('tutorial must begin with anchor move');
 if(!(await card('practice').locator('.canvas-guide').textContent()).includes('Blauen Ankerpunkt ziehen')||!(await card('practice').locator('.canvas-guide').textContent()).includes('Drag the blue anchor point')||await card('practice').locator('.guide-ring').count()!==1)throw Error('in-canvas anchor guidance');
 await gateButton.click();if(!(await gate.isHidden())||await card('practice').locator('[data-role="toggle"]').isHidden())throw Error('start gate dismissal');const p0=await path('practice');await drag(card('practice').locator('[data-node="2"]'));if(await path('practice')===p0||!(await p.locator('[data-step="0"]').getAttribute('class')).includes('done')||!(await p.locator('#name').textContent()).includes('Schritt 2')||await card('practice').locator('[data-role="add"]').isDisabled())throw Error('anchor tutorial step');
 if(!(await card('practice').locator('.canvas-guide').textContent()).includes('„+ Ankerpunkt“ wählen')||!(await card('practice').locator('.canvas-guide').textContent()).includes('Select “+ Anchor”'))throw Error('in-canvas insert guidance');
 await card('practice').locator('[data-role="add"]').click();await clickPath(card('practice').locator('[data-segment="0"]'));if(!(await p.locator('[data-step="1"]').getAttribute('class')).includes('done')||!(await p.locator('#name').textContent()).includes('Schritt 3')||await card('practice').locator('.handle').count()===0)throw Error('insert tutorial step');
 if(!(await card('practice').locator('.canvas-guide').textContent()).includes('Orangen Steuerpunkt ziehen')||!(await card('practice').locator('.canvas-guide').textContent()).includes('Drag the orange control point'))throw Error('in-canvas control guidance');
 await drag(card('practice').locator('.handle').first(),18,14);if(!(await p.locator('[data-step="2"]').getAttribute('class')).includes('done')||await p.locator('#name').textContent()!=='Übung fertig / Practice complete'||await card('practice').locator('[data-role="finish"]').isDisabled())throw Error('control tutorial step');
 await card('practice').locator('[data-role="finish"]').click();if(!(await p.locator('#next').isEnabled())||await p.evaluate(()=>results.length)!==0)throw Error('practice completion');await p.locator('#next').click();
 {const formalState={badge:await p.locator('#taskBadge').textContent(),cards:await p.locator('.editor-card').count(),progressHidden:await p.locator('#progressBlock').isHidden(),tutorialHidden:await p.locator('#tutorialSteps').isHidden()};if(!formalState.badge.startsWith('Aufgabe 1 / 4 · Task ·')||formalState.cards!==4||formalState.progressHidden||!formalState.tutorialHidden)throw Error('formal start '+JSON.stringify(formalState))}
 const methods=['adavec','ours','ground_truth','live'];if(JSON.stringify(await p.locator('.editor-card').evaluateAll(cards=>cards.map(c=>c.dataset.method)))!==JSON.stringify(methods))throw Error('option order');
 for(const m of methods){const expected=await p.evaluate(m=>TASKS[0].predictions[m].original_anchor_count,m),overlay=card(m).locator('.target-overlay');if(await card(m).locator('.node').count()!==expected||await card(m).locator('[data-role="startGate"]').isHidden())throw Error('native anchors or formal gate '+m);if(await overlay.count()!==1||await overlay.getAttribute('d')!==await p.evaluate(()=>TASKS[0].after)||await overlay.getAttribute('clip-path')!==null||await overlay.getAttribute('pointer-events')!=='none'||await card(m).locator('.canvas-task-hint').count())throw Error('full target guide '+m);const order=await card(m).locator('svg').evaluate(svg=>[...svg.children].map(e=>e.getAttribute('class')));if(order.indexOf('target-overlay')<order.indexOf('editable-path')||order.indexOf('target-overlay')>order.indexOf('node'))throw Error('target overlay stacking '+m)}
 await card('ours').locator('[data-role="startGateButton"]').click();await drag(card('ours').locator('[data-node="3"]'));await card('ours').locator('[data-role="finish"]').click();if(await p.locator('#totalProgress').getAttribute('value')!=='1'||await card('ours').locator('[data-role="toggle"]').textContent()!=='Weiter bearbeiten / Edit again')throw Error('formal completion');{const timing=await p.evaluate(()=>results[0]);if(timing.trial_key!=='B1641:B'||timing.task_id!=='B1641'||timing.method_code!=='B'||timing.timer_protocol!=='per_task_method_active_v1'||!timing.trial_started_at||timing.active_time_seconds<=0||timing.wall_time_seconds<timing.active_time_seconds||timing.elapsed_seconds!==timing.active_time_seconds||!Array.isArray(timing.active_intervals)||timing.active_intervals.length!==1)throw Error('per task-method timing '+JSON.stringify(timing))}
 await card('ours').locator('[data-role="toggle"]').click();if(await p.locator('#totalProgress').getAttribute('value')!=='0')throw Error('completion cancellation');await card('ours').locator('[data-role="finish"]').click();await card('adavec').locator('[data-role="startGateButton"]').click();await card('adavec').locator('[data-role="abandon"]').click();
 for(const m of ['ground_truth','live']){await card(m).locator('[data-role="startGateButton"]').click();await card(m).locator('[data-role="abandon"]').click()}
 for(let i=1;i<4;i++){await p.locator('#next').click();if(!(await p.locator('#taskBadge').textContent()).startsWith(`Aufgabe ${i+1} / 4 · Task ·`))throw Error('task advance '+i);for(const m of methods){if(await card(m).locator('[data-role="startGate"]').isHidden())throw Error(`task ${i+1} missing independent start gate ${m}`);await card(m).locator('[data-role="startGateButton"]').click();await card(m).locator('[data-role="abandon"]').click()}}
 if(await p.locator('#totalProgress').getAttribute('value')!=='16'||await p.locator('#submit').isHidden()||!(await p.locator('#next').isHidden())||!(await p.locator('#submit').isEnabled()))throw Error('final submit state');
 const dl=p.waitForEvent('download');await p.locator('#submit').click();const f=await dl,s=await f.createReadStream();let text='';for await(const c of s)text+=c;const out=JSON.parse(text),mapping={A:'AdaVec',B:'Ours',C:'Ground Truth',D:'LIVE'},cells=new Set(out.records.map(r=>r.trial_key));if(out.schema!=='anchorflow-benchmark2400-editor-v3'||out.record_grain!=='one participant session × one task × one method'||out.timer_protocol!=='per_task_method_active_v1'||!out.study_session_id||out.participant_profile?.svg_experience!=='general'||out.participant_profile?.svg_experience_label!=='General SVG experience'||out.records.length!==16||cells.size!==16||out.records.some(r=>r.participant_svg_experience!=='general'||!r.sample_id||![1641,973,1407,724].includes(r.benchmark_ordinal)||mapping[r.method_code]!==r.method||r.trial_key!==`${r.task_id}:${r.method_code}`||r.trial_id!==`${out.study_session_id}:${r.trial_key}`||!r.trial_started_at||typeof r.active_time_seconds!=='number'||typeof r.wall_time_seconds!=='number'||r.wall_time_seconds<r.active_time_seconds||r.elapsed_seconds!==r.active_time_seconds||!Array.isArray(r.active_intervals)||!r.active_intervals.length))throw Error('submitted records');if(await p.locator('#submit').textContent()!=='Erneut teilen / Share again')throw Error('submit confirmation');
 for(let i=0;i<4;i++){await p.evaluate(i=>load(i),i);for(const m of methods){const expected=await p.evaluate(([i,m])=>TASKS[i].predictions[m].original_anchor_count,[i,m]);if(await card(m).locator('.node').count()!==expected)throw Error(`task ${i} ${m}`)}await p.screenshot({path:__dirname+`/preview_task_${i+1}.png`,fullPage:true})}
 await p.evaluate(()=>load(0));if(/[\u4e00-\u9fff]/.test(await p.locator('body').innerText()))throw Error('Chinese participant-facing copy remains');await p.screenshot({path:__dirname+'/preview_benchmark.png',fullPage:true});await p.reload();await p.screenshot({path:__dirname+'/preview_intro_v16.png',fullPage:true});if(errors.length)throw Error(errors.join());console.log('PASS: required German-English SVG experience profile, independent task-method timers, A=AdaVec, B=Ours, C=Ground Truth, D=LIVE, export mapping, and 16 native paths.');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
